services : 
  front : 
    build : 
      context : ./frontend
      dockerfile : ./Dockerfile
    ports : 
      - "8080:8080"

  back : 
    build :
      # context: ./backend
      dockerfile : ./backend/Dockerfile
    ports : 
      - "3000:3000"
    env_file:
    - .env
  
  data : 
    build:
      context : ./data
      dockerfile : ./Dockerfile

  db : 
    build :
      context : ./backend/database
      dockerfile : ./Dockerfile
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=db
    volumes:
      - db-data:/var/lib/pgsql/data

volumes:
  db-data: