services : 
  front : 
    build : 
      context : ./frontend
      dockerfile : ./Dockerfile
    ports : 
      - "8080:80"

  back : 
    build :
      # context: ./backend
      dockerfile : ./backend/Dockerfile
    ports : 
      - "3000:3000"
  
  data : 
    build:
      context : ./data
      dockerfile : ./Dockerfile

  db : 
    build :
      context : ./backend/database
      dockerfile : ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: example
    