name: Mirror
on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Mirror Repository
        run: |

          git clone --bare git@github.com:yAnn-99/JOB_AGGREGATOR.git
          cd JOB_AGGREGATOR.git
          
          git push --mirror git@github.com:EpitechBachelorPromo2028/B-YEP-200-PAR-2-1-jobaggregator-10.git